openapi: 3.0.0
info:
  title: Dept API
  version: 1.0.0
paths:
  /app/dept:
    get:
      summary: Rest DB API
      operationId: dept
      responses:
        '200':
          description: List of departments
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    deptno:
                      type: integer
                      format: int32
                      description: Department number
                    dname:
                      type: string
                      description: Department name
                    loc:
                      type: string
                      description: Location 
  /app/info:
    get:
      summary: Rest Info API
      responses:
        200:
          description: Information about the API
          content:
            text/html:
              schema:
                type: string
